data_ingestion:
  bucket_name: hotel_booking_pred
  dataset_name: hotel_booking.csv
  train_ratio: 0.8
  test_ratio: 0.2

data_processing:
  categorical_cols:
    - type of meal
    - car parking space
    - room type
    - market segment type
    - repeated
    - booking status
  numerical_cols:
    - number of adults
    - number of children
    - number of weekend nights
    - number of week nights
    - lead time
    - repeated
    - P-C
    - P-not-C
    - average price
    - special requests
  skew_threshold: 5
  num_features_to_select: 10